#!/usr/bin/env python
import os
import sys
from django.core.wsgi import get_wsgi_application

# on openshift cart?
if 'OPENSHIFT_REPO_DIR' in os.environ:
    sys.path.append(
        os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'source'))
else:
    sys.path.append(os.path.join(os.path.dirname(__file__), 'source'))

# product stage
os.environ['DJANGO_SETTINGS_MODULE'] = 'etc.settings.pro'

application = get_wsgi_application()
